name: NPM Package

on:
  pull_request:
    branches:
    - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Change to package directory
        run: cd packages/react-form-model-controller
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm run build
      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
