name: NPM Package

on:
  pull_request:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Change to package directory and install dependencies
        run: |
          cd packages/react-form-model-controller
          pnpm install
      - name: Run build
        run: |
          cd packages/react-form-model-controller
          pnpm run build --no-git-checks
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/react-form-model-controller
          pnpm publish --access public
